# Workflow based on a template by @cpintado

# name of the workflow: will be visible in the dashboard and in Splunk
name: template by @cpintado

# Trigger the workflow on push (needed for cache)
on:
  push:

# list of jobs, creat more than one if necessary
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Gets the directory that will be used by PHP composer to store its dependencies
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        composer config cache-files-dir
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
